environment:
  global: {}
init: []
install:
  - cmd: 'setlocal & python -m pip install pip -U & endlocal'
  - cmd: "setlocal & SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH% & pip2 install nose numpy psutil & endlocal"
  - cmd: "setlocal & SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH% & pip2 install git+https://github.com/3drobotics/dronekit-sitl-runner.git & endlocal"
build_script:
  - cmd: 'setlocal & python setup.py install & endlocal'
  - cmd: "setlocal & SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH% & nosetests tests\\web & endlocal"
  - cmd: "setlocal & SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH% & cd tests & python -m sitl & endlocal"
clone_depth: 10
cache:
  - '%CYG_CACHE%'
test: 'off'
branches:
  only:
    - master
